# Copyright 2023 seL4 Project a Series of LF Projects, LLC.
# SPDX-License-Identifier: BSD-2-Clause
##
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: seL4
description: "The seL4 main website.  Pull requests are welcome."
url: "https://sel4.systems"
static_url: "https://sel4.systems"
baseurl: "" # the subpath of your site, e.g. /blog
git_repo: https://github.com/seL4/website
github_username: seL4

collections:
  - "news-items"

# Front matter defaults:
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      background: true

# Build settings

plugins:
  # Adds a sitemap.xml to site for webcrawlers
  - jekyll-sitemap
  # Allow multiple urls to redirect to a single page
  - jekyll-redirect-from
  # For tailwind postcss
  - jekyll-postcss-v2
  # For icons
  - jekyll-inline-svg
  # Generate table of contents for toc: true in the frontmatter
  - jekyll-toc


strict_front_matter: true

optional_front_matter:
# Set this to false if you want .md files to be accessible also
  remove_originals: true

svg:
  optimize: true

exclude:
  - Makefile
  - README.md
  - layout.md
  - LICENSES/
  - docker/
  - _news-items/9999-12-31-template.md
  - node_modules/
  - vendor/
  - package-lock.json
  - package.json
  - postcss.config.js
  - "**/*.license"
  - .bundle/
  - .github/
  - .git/
  - .gitignore
  - .reuse/
  - colours.html
