version = 1

SPDX-PackageName = "seL4.systems"
SPDX-PackageSupplier = "seL4 Foundation"
SPDX-PackageDownloadLocation = "https://github.com/seL4/website/"

[[annotations]]
path = [
    "_data/menu.json",
    "_data/footer.json",
    "_data/members.json",
    "_data/platforms.json",
    "_data/sponsors.json",
    "_includes/menu.html",
    ".bundle/config",
    "Gemfile.lock",
    ".ruby-version",
    ".nvmrc",
]
SPDX-FileCopyrightText = "2024 seL4 Project a Series of LF Projects, LLC."
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
    "images/icons/android*.png",
    "images/icons/apple-touch-icon*.png",
    "images/icons/mstile*.png",
    "images/icons/favicon*.png",
    "images/icons/favicon.ico",
    "images/icons/manifest.json",
    "images/icons/browserconfig.xml",
    "images/seL4-short.svg",
    "favicon.ico",
    "robots.txt",
    "**/**.pdf",
    "About/whitepaper.svg",
    "security.asc",
]
SPDX-FileCopyrightText = "2020 seL4 Project a Series of LF Projects, LLC."
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "About/webserver.svg"
SPDX-FileCopyrightText = "UNSW"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
  "_includes/abstracts/*/*.html",
]
SPDX-FileCopyrightText = "Various. Each abstract is copyright of the talk author."
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
  "_icons/*.svg",
  "_icons/other/external.svg",
  "images/check-badge.svg",
  "images/code-bracket.svg",
]
SPDX-FileCopyrightText = "Tailwind Labs"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "Foundation/Board/**.jpg",
  "Foundation/Board/**.png",
  "images/tsc/**",
  "images/summit/**",
  "images/acm**",
]
SPDX-FileCopyrightText = "various"
SPDX-License-Identifier = "LicenseRef-PhotoLicence"

[[annotations]]
path = [
  "Foundation/Membership/LOGOS/**",
  "Foundation/Summit/2024/Sponsors/*.svg",
]
SPDX-FileCopyrightText = "Various. Each logo is copyright to the organisation owning that logo."
SPDX-License-Identifier = "LicenseRef-PhotoLicence"

[[annotations]]
path = "**/**.patch"
SPDX-FileCopyrightText = "2020 seL4 Project a Series of LF Projects, LLC."
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = ["Info/Docs/u-boot-working-rpi3-32bit-v2017.11.bin", "Info/Hardware/sabreLite/u-boot.bin"]
SPDX-FileCopyrightText = "Wolfgang Denk and others 2019"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
    "js/callgraph.json",
    "package.json",
    "package-lock.json",
]
SPDX-FileCopyrightText = "Copyright 2025 Proofcraft Pty ltd"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
    "images/pr.svg",
    "images/res_paper.svg",
    "images/screenshot-isabelle-dark.png",
    "images/screenshot-kernel-elf.png",
    "images/screenshot-proofs.png",
    "images/code-skewed.png",
    "images/git-commits.svg",
    "images/licensing.drawio.svg",
    "images/tries-shutterstock/0sorries.jpg",
    "_icons/other/registered-tm.svg",
]
SPDX-FileCopyrightText = "Copyright 2025 Proofcraft Pty ltd"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "images/circuit-boards.png",
]
SPDX-FileCopyrightText = "Copyright Shutterstock"
SPDX-License-Identifier = "LicenseRef-Shutterstock"


[[annotations]]
path = "_icons/other/C.svg"
SPDX-FileCopyrightText = "Rezonansowy"
SPDX-License-Identifier = "CC0-1.0"
from = "https://en.m.wikipedia.org/wiki/File:The_C_Programming_Language_logo.svg"

[[annotations]]
path = "_icons/other/rust-logo-blk.svg"
SPDX-FileCopyrightText = "Copyright 2023 Rust Foundation"
SPDX-License-Identifier = "CC-BY-4.0"
from = "https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/"

[[annotations]]
path = "_icons/other/Elixir.svg"
SPDX-FileCopyrightText = "Copyright 2025 Elixir Team"
SPDX-License-Identifier = "LicenseRef-Elixir"
from = "https://elixir-lang.org/trademarks"

[[annotations]]
path = "_icons/other/github.svg"
SPDX-FileCopyrightText = "Copyright 2025 GitHub, Inc"
SPDX-License-Identifier = "LicenseRef-GitHubLogo"

[[annotations]]
path = "_icons/other/mastodon.svg"
SPDX-FileCopyrightText = "Copyright 2025 Mastodon gGmbH"
SPDX-License-Identifier = "LicenseRef-MastodonLogo"

[[annotations]]
path = "_icons/other/linkedin.svg"
SPDX-FileCopyrightText = "Copyright 2025 LinkedIn Corporation"
SPDX-License-Identifier = "LicenseRef-LinkedInLogo"

[[annotations]]
path = "_icons/other/youtube.svg"
SPDX-FileCopyrightText = "Copyright 2025 YouTube"
SPDX-License-Identifier = "LicenseRef-YouTubeLogo"

[[annotations]]
path = "_icons/other/python-logo-only.svg"
SPDX-FileCopyrightText = "Copyright 2025 Python Software Foundation"
SPDX-License-Identifier = "LicenseRef-PythonLogo"
